version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13
    commands:
      - echo "Running on Go"
      # Fetch all dependencies
      - go get ./...
  pre_build:
    commands:
      - ls
  build:
    commands:
      - echo Building *.go files
      - cd createTask/
      - go build
      - cd ..
      - cd getUserTasks/
      - go build
      - cd ..
  post_build:
    commands:
      - echo Sending to s3
      - zip createTask/createTask.zip createTask/createTask
      - aws s3 cp createTask/createTask.zip s3://taskmanagerapp-deploybucket
      - zip getUserTasks/getUserTasks.zip getUserTasks/getUserTasks
      - aws s3 cp getUserTasks/getUserTasks.zip s3://taskmanagerapp-deploybucket